trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/partial'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: PartialBuild
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.x'  

    - script: |
        echo "Restoring..."
        dotnet restore
        echo "Building..."
        dotnet build --configuration $(buildConfiguration) --no-restore
      displayName: 'Dotnet Restore & Build'

    - script: |
        echo "Detecting changed files..."
        git fetch origin main
        CHANGED_FILES=$(git diff --name-only origin/main HEAD)
        echo "Changed files: $CHANGED_FILES"
        echo "$CHANGED_FILES" > changed_files.txt
      displayName: 'Detect Changed Files'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p "$(outputDir)"
          while read file; do
            if [[ "$file" == *.dll || "$file" == *.exe ]]; then
              found=$(find . -type f -name "$(basename "$file")")
              for f in $found; do
                echo "Copying $f to $(outputDir)"
                cp --parents "$f" "$(outputDir)" || true
              done
            fi
          done < changed_files.txt
      displayName: 'Copy Only Changed Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'partial-artifacts'
        publishLocation: 'Container'
